//Do not edit this file directly
//Copy this file to your main app directory to make changes
const config = {
    components: [
        { name: 'datetime' },
        { name: 'device' },
        { name: 'event' },
        { name: 'expect' },
        { name: 'room' },
        { name: 'variable' },
        { name: 'scene' },
    ],
    logging: {
        levels: {
            default: 'debug',
        },
    },
}

module.exports = config
